export const colors = {
  yellow: '#E3B53C',
  orange: '#E3823C',
  red: '#E33C3C',
  white: '#ffffff',
  black: '#000000',
  green: '#1ab932',
  blue: '#1877F2',
  lightDark: '#23203F',
  dark: '#141326',
  transparentYellow: 'rgba(227, 181, 60, 0.3)'
};

export const darkColors = {
  primary: colors.yellow,
  secondary: colors.orange,
  text: colors.white,
  background: colors.dark,
  secondaryBackground: colors.lightDark,
  white: colors.white,
  black: colors.black,
  orange: colors.orange,
  error: colors.red,
  success: colors.green,
  warning: colors.yellow,
  info: colors.yellow,
  inputBorder: colors.white,
  rippleColor: colors.transparentYellow,
  primaryGradient: [colors.yellow, colors.red],
  secondaryGradient: [colors.orange, colors.red],
  bgGradient: [colors.orange, 'transparent'],
};

export const lightColors = {
  primary: colors.yellow,
  secondary: colors.orange,
  text: colors.black,
  background: colors.white,
  secondaryBackground: colors.lightDark,
  white: colors.white,
  black: colors.black,
  orange: colors.orange,
  error: colors.red,
  success: colors.green,
  warning: colors.yellow,
  info: colors.yellow,
  inputBorder: colors.black,
  rippleColor: colors.transparentYellow,
  primaryGradient: [colors.yellow, colors.red],
  secondaryGradient: [colors.orange, colors.red],
  bgGradient: [colors.orange, 'transparent'],
};
